#! /usr/bin/env python

from rtapebbletest import configwrapper

if __name__ == "__main__":
    configwrapper.ConfigWrapper.print_example_yaml()


# vim: set expandtab ts=4 sw=4 filetype=python fileencoding=utf8 syntax=python:
