#! /usr/bin/env python
# vim: set expandtab ts=4 sw=4 filetype=python fileencoding=utf8:

import argparse

from rtapebbletest.configwrapper import ConfigWrapper

if __name__ == "__main__":

    ap = argparse.ArgumentParser(
        description="Print a value from the config file")

    ap.add_argument("yaml_file_name")
    ap.add_argument("property")

    args = ap.parse_args()

    cw = ConfigWrapper.load_yaml(args.yaml_file_name)

    print(getattr(cw, args.property))
